"""Exportación de modelos de dominio para AAdventure."""

from domains.base import Entity
from domains.conversation import ConversationRecord
from domains.items import Item
from domains.story_config import StoryConfig
from domains.lore import (
    ActionType,
    ConditionGroup,
    EntityCondition,
    EntityConditionType,
    LoreBlock,
    LoreBlockState,
    LoreBlockType,
    LoreEffects,
    SubCondition,
)
from domains.npcs import NPC, NPCMotivations
from domains.player import Player
from domains.game_state import (
    EntityMapItem,
    EntityMapLocation,
    EntityMapNPC,
    EntityMapPlace,
    GameState,
    Inventory,
    LoreBlockHierarchy,
    NotebookEntry,
)
from domains.system.system_domains import (
    ContextType,
    ExplainLookNarratorCtx,
    ExplainLookResponse,
    ExplainLookResult,
    MoveNarratorCtx,
    MoveNarratorResponse,
    MoveNarratorResult,
    ResponseType,
    ResultType,
    RuntimeState,
)
from domains.world import Connection, Location, Place, World
from domains.projections import (
    ActionCommandProjection,
    AvailableActionsProjection,
    ConnectionProjection,
    GameSnapshotProjection,
    GameStateProjection,
    InventoryItemDTO,
    InventoryProjection,
    LocationHierarchyProjection,
    LoreBlockDetailProjection,
    LoreConditionDetailProjection,
    LoreGraphProjection,
    MapItemDTO,
    MapLocationDTO,
    MapNPCDTO,
    MapPlaceDTO,
    MoveOptionProjection,
    NotebookProjection,
    PlaceDetailProjection,
    PlaceProjection,
    PlayerSummaryProjection,
    RagAntennaScoreProjection,
    RagEvaluationProjection,
    TurnDebugProjection,
    TurnOutput,
    TurnResultProjection,
    UIStateProjection,
    WorldHierarchyProjection,
    WorldMapProjection,
)

__all__ = [
    "Entity",
    "Item",
    "StoryConfig",
    "World",
    "Location",
    "Place",
    "Connection",
    "Player",
    "NPC",
    "NPCMotivations",
    "LoreBlock",
    "LoreBlockState",
    "LoreBlockType",
    "ActionType",
    "EntityConditionType",
    "SubCondition",
    "EntityCondition",
    "ConditionGroup",
    "LoreEffects",
    "ConversationRecord",
    "ContextType",
    "ResponseType",
    "ResultType",
    "GameState",
    "Inventory",
    "EntityMapItem",
    "EntityMapLocation",
    "EntityMapNPC",
    "EntityMapPlace",
    "LoreBlockHierarchy",
    "NotebookEntry",
    "RuntimeState",
    "ActionCommandProjection",
    "MoveNarratorCtx",
    "MoveNarratorResponse",
    "MoveNarratorResult",
    "ExplainLookNarratorCtx",
    "ExplainLookResponse",
    "ExplainLookResult",
    # Projections & DTOs
    "TurnOutput",
    "MapItemDTO",
    "MapNPCDTO",
    "MapPlaceDTO",
    "MapLocationDTO",
    "WorldMapProjection",
    "InventoryItemDTO",
    "InventoryProjection",
    "NotebookProjection",
    "TurnResultProjection",
    "PlaceProjection",
    "LocationHierarchyProjection",
    "WorldHierarchyProjection",
    "UIStateProjection",
    "MoveOptionProjection",
    "AvailableActionsProjection",
    "PlayerSummaryProjection",
    "GameSnapshotProjection",
    "GameStateProjection",
    "PlaceDetailProjection",
    "ConnectionProjection",
    "LoreBlockDetailProjection",
    "LoreConditionDetailProjection",
    "LoreGraphProjection",
    "RagAntennaScoreProjection",
    "RagEvaluationProjection",
    "TurnDebugProjection",
]
