"""Exportación de modelos de dominio para AAdventure."""

from domains.base import Entity
from domains.conversation import ConversationRecord
from domains.items import Item, GameObject
from domains.story_config import StoryConfig
from domains.lore import EntityCondition, LoreBlock, LoreBlockState, LoreEffects
from domains.npcs import NPC, NPCInfo, NPCMotivations
from domains.player import Player
from domains.system.system_domains import (
    ActionCommand,
    ContextType,
    ExplainLookNarratorCtx,
    ExplainLookResponse,
    ExplainLookResult,
    GameState,
    MoveNarratorCtx,
    MoveNarratorResponse,
    MoveNarratorResult,
    ResponseType,
    ResultType,
    RuntimeState,
)
from domains.world import Connection, Location, LocationInfo, Place, PlaceInfo, World
from domains.projections import (
    AvailableActionsProjection,
    ConnectionProjection,
    GameSnapshotProjection,
    GameStateProjection,
    LocationHierarchyProjection,
    MoveOptionProjection,
    PlaceDetailProjection,
    PlaceProjection,
    PlayerSummaryProjection,
    LoreBlockDetailProjection,
    LoreConditionDetailProjection,
    LoreGraphProjection,
    RagAntennaScoreProjection,
    RagEvaluationProjection,
    TurnResultProjection,
    UIStateProjection,
    WorldHierarchyProjection,
)

__all__ = [
    "Entity",
    "Item",
    "GameObject",
    "StoryConfig",
    "World",
    "Location",
    "Place",
    "Connection",
    "Player",
    "NPC",
    "NPCMotivations",
    "LoreBlock",
    "LoreBlockState",
    "EntityCondition",
    "LoreEffects",
    "ConversationRecord",
    "ContextType",
    "ResponseType",
    "ResultType",
    "GameState",
    "RuntimeState",
    "PlaceProjection",
    "ActionCommand",
    "LocationInfo",
    "PlaceInfo",
    "NPCInfo",
    "MoveNarratorCtx",
    "MoveNarratorResponse",
    "MoveNarratorResult",
    "ExplainLookNarratorCtx",
    "ExplainLookResponse",
    "ExplainLookResult",
    "UIStateProjection",
    "LocationHierarchyProjection",
    "WorldHierarchyProjection",
    "MoveOptionProjection",
    "AvailableActionsProjection",
    "PlayerSummaryProjection",
    "GameSnapshotProjection",
    "GameStateProjection",
    "PlaceDetailProjection",
    "ConnectionProjection",
    "LoreBlockDetailProjection",
    "LoreConditionDetailProjection",
    "LoreGraphProjection",
    "RagAntennaScoreProjection",
    "RagEvaluationProjection",
    "TurnResultProjection",
]
